name = "the-scene-co"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "the_scene_co_db"
database_name = "the-scene-co-db"
database_id = "78963f57-36d8-4dd5-badf-78116887f292"

[[r2_buckets]]
binding = "the_scene_co_media"
bucket_name = "the-scene-co-media"

[vars]
ADMIN_PASSWORD_HASH = ""
